name: Build and Deploy to deploy branch

on:
  push:
    branches: [main]
    paths-ignore:
      - 'public/A2GS101V1/**'
      - 'scraper/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install & Build
        working-directory: ./
        run: |
          bun install
          bun run build

      - name: Deploy to deploy branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: ./dist
          force_orphan: true
